name: Get list

on:
  repository_dispatch:
    types: [get_list]

jobs:
  get_list:
    runs-on: ubuntu-latest
    steps:
      - name: Send URL to server
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Sending URL"

          curl -X POST "https://drive-ygsv.onrender.com/youtube-list" \
            -H "Content-Type: application/json" \
            -d "$(echo "$PAYLOAD" | jq '{url: .url, token: .token}')" \
            --fail-with-body \
            --show-error
