name: Groq chat

on:
  repository_dispatch:
    types: [groq_chat]

jobs:
  groq_chat:
    runs-on: ubuntu-latest
    steps:
      - name: Send prompt to server
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Sending prompt"

          curl -X POST "https://drive-ygsv.onrender.com/groq-chat" \
            -H "Content-Type: application/json" \
            -d "$(echo "$PAYLOAD" | jq '{prompt: .prompt}')" \
            --fail-with-body \
            --show-error
