name: Upload URL

on:
  repository_dispatch:
    types: [proxy_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Send URLs to server
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Sending URLs"

          curl -X POST "https://drive-ygsv.onrender.com/upload" \
            -H "Content-Type: application/json" \
            -d "$(echo "$PAYLOAD" | jq '{url: .url}')" \
            --fail-with-body \
            --show-error
