name: Mirror site

on:
  repository_dispatch:
    types: [mirror_site]

jobs:
  mirror_site:
    runs-on: ubuntu-latest
    steps:
      - name: Send URL to server
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Sending URL"

          curl -X POST "https://drive-ygsv.onrender.com/mirror-site" \
            -H "Content-Type: application/json" \
            -d "$(echo "$PAYLOAD" | jq '{url: .url}')" \
            --fail-with-body \
            --show-error
