name: Download Job

on:
  repository_dispatch:
    types: [download_request]

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download file
        run: |
          mkdir -p downloads

          URL="${{ github.event.client_payload.url }}"
          REQ_ID="${{ github.event.client_payload.req_id }}"

          echo "Downloading: $URL"

          curl -L --max-time 60 -o "downloads/file" "$URL"

          echo "$REQ_ID" > downloads/request_id.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ github.event.client_payload.req_id }}
          path: downloads/