name: Upload youtube

on:
  repository_dispatch:
    types: [youtube_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Send URLs to server
        run: |
          echo "Sending URLs"

          curl -X POST "https://drive-ygsv.onrender.com/upload-youtube" \
            -H "Content-Type: application/json" \
            -d '${{ toJson(github.event.client_payload) }}' \
            --fail-with-body \
            --show-error
